# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9ecee5652aa05cab40cb46908b374c5d86eb83960a8125c7e3026bc6c3802399a8f8a230f0c1a8beda70b9c96c36e11568382753eedc677de492cd1296841b3

test:
  secret_key_base: deae3a3e851d6424a717c3da13da86c3104f8a2da43ae20ed14982bd8f5c1dd89c8712d61e0059523c1be1967ec3acea0d616be6421a5cb46c3f843d1d3a109b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
